### PR TITLE
Add how to start the frontend

### PR DESCRIPTION
**Pull request by markusschuh**

### CODE REVIEW

**Comment by hohwille** [comment]
@markusschuh Thanks for this PR. I am happy to merge it.
However be informed that all these `devonfw` documentation that do not belong to `devon4j` itself need to be moved out here. 
* Setting up the IDE should go to `devon-ide` (or more precisely is already documented there) and only be linked here if at all.
* Setting up my-thai-start should go to `my-thai-star` and does not make any sense to document in the stacks...
* General guides how to work with github, pull-requests, asciidoc, etc. should also not be part of devon4j but go to the `devonfw` repository itself (or for asciidoc, etc. link to `devon-docgen`).

**Comment by hohwille** [comment]
Does anyone know why travis hangs? Why do we have 2 travis checks in the PR with the same title after all?

**Comment by markusschuh** [comment]
If fully agree with your plan. This pull request was just based on the fact that some developers still seem to use this - without any doubt aged - documentation more or less successfully. Just the frontend startup was a too high challenge to see a first success - an **accessible** sample application started from the own IDE.  `my-thai-star` itself currently does not seem to contain a related documentation,

But all that optimized structure must keep in mind, that there needs to be an easy startup path into the devonfw world for a Newbee. This should be a one pager like this current devonfw-ide-setup - of course describing the up-to-date process. Potentially located within the `my-thai-star` repository. With links to the related gory details for all used components. Or as an intro chapter inside `devonfw-tutorial-sources` - where a developer could dive far deeper into the devonfw framework. 

I can imagine to take that task. But I am still struggling what **is** the up-to-date process of bringing up a first tutorial application in a fresh devon ide since that is a currently too fast in time moving target for me.

**Comment by sjimenez77** [comment]
Hi @hohwille, I think that the Travis process that is hanged is because of this repository still contains the old Travis integration in Services section:

image

It should be removed in order to keep the current travis-ci.com job.

**Comment by hohwille** [comment]
@sjimenez77 👍 Awesome catch. Thanks for the hint. I deleted the oboslte Travis CI service now. Error should not show up anymore for updated or new PRs from now on. Very pro-active support from you @sjimenez77 !!!

**Comment by hohwille** [comment]
> If fully agree with your plan. This pull request was just based on the fact that some developers still seem to use this - without any doubt aged - documentation more or less successfully. Just the frontend startup was a too high challenge to see a first success - an **accessible** sample application started from the own IDE. `my-thai-star` itself currently does not seem to contain a related documentation,
> 

absoultely right and thanks for your PR.

> But all that optimized structure must keep in mind, that there needs to be an easy startup path into the devonfw world for a Newbee. This should be a one pager like this current devonfw-ide-setup - of course describing the up-to-date process. Potentially located within the `my-thai-star` repository. With links to the related gory details for all used components. Or as an intro chapter inside `devonfw-tutorial-sources` - where a developer could dive far deeper into the devonfw framework.
>
> I can imagine to take that task. But I am still struggling what **is** the up-to-date process of bringing up a first tutorial application in a fresh devon ide since that is a currently too fast in time moving target for me.

I undertand what you mean. We are a very active community and things are changing. However, there is a lot stabilizing already.
Please not that there are people already working on this topic such as @dhelmke or @phschimm
So you do not need to put your energy into this. IMHO contributions to `devon-ide` from you would be more valuable. But if you are thinking about working on a particular issue, be sure that it is not already assigned and first write a comment (or if permitted, assign yourself) and wait a day before you invest some work into starting a PR...

**Pull request merged**
