### PR TITLE
Added MasterCto for reuse of the most common thing about CTOs

### PR DESCRIPTION
**Pull request by hohwille**

### CODE REVIEW

**Comment by hohwille** [comment]
Still waiting for review. As we missed 3.0.0 I assigned 3.1.0 and hope to get review feedback soon. It is a small and simple change that introduces a new feature (not breaking existing stuff).

**Comment by hohwille** [comment]
Please review!

**Comment by hohwille** [comment]
Open for more than 4 months without any review feedback. Can we please get into discussion (e.g. do we need further abstraction via Interface to allow a MasterCto implementation to customize the property name (currently fixed to `master`) for any reason? How about CobiGen Template Adoption?
This is such a small but obvious improvement. Come on guys...

**Comment by hohwille** [comment]
@maybeec can we merge now?

**Comment by maybeec** [comment]
yes fine for me

**Pull request merged**
