### PR TITLE
#96: update to spring-boot 2.1.9

### PR DESCRIPTION
**Pull request by hohwille**
update to spring-boot `2.1.9.RELEASE` for issue #96

### CODE REVIEW

**Comment by hohwille** [comment]
We still seem to have guava 17.0 with this.
We need to override it to have guava version `27.1-jre`.
AFAIK we are getting guava from `query-dslcore`. Maybe there is also an update of querydsl available. Otherwise we should try to override guava in BOM or according module (`basic-core`).

**Comment by hohwille** [comment]
Build is looking good now. Should we include this fix into the release?
According to my tests all seems to work.

**Comment by hohwille** [comment]
I have rerun the OWASP check and guava seems to be fixed now. I also verified that now the archetype uses guava `28.1-jre` as intendet. So at least one CVE fixed and some other updates included.

**Comment by vapadwal** [comment]
I have done the basic testing creating a project with this and it seems we dont have issue here

**Comment by hohwille** [comment]
I also rely on spring-boot who did good quality assurance. Also we still have the ability to ship a bugfix release. Being agile and keep updating is after all better than always being frigthened about what could break or go wrong. As we all have tested and automated tests are also fine, I will go for it. Thanks @vapadwal for testing and review.

**Pull request merged**
