### PR TITLE
#171: radical cleanup of archetype

### PR DESCRIPTION
**Pull request by hohwille**
Additional go of #171

### CODE REVIEW

**Comment by maihacke** [comment]
It testet this locally with:

`mvn install:install-file -Dfile=./target/devon4j-template-server-2020.04.001-SNAPSHOT.jar -DpomFile=./pom.xml`

`mvn -f ./pom.xml archetype:update-local-catalog`

`mvn archetype:generate -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server -DinteractiveMode=false -Dpackage=com.demo.snapshotsample -DartifactId=snapshotsample -DgroupId=com.demo -Dversion=1.0.0-SNAPSHOT -DarchetypeVersion=2020.04.001-SNAPSHOT -DarchetypeCatalog=local`

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [com.devonfw.java.templates:devon4j-template-server:2020.04.001-SNAPSHOT] found in catalog local
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: devon4j-template-server:2020.04.001-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.demo
[INFO] Parameter: artifactId, Value: snapshotsample
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: package, Value: com.demo.snapshotsample
[INFO] Parameter: packageInPathFormat, Value: com/demo/snapshotsample
[INFO] Parameter: package, Value: com.demo.snapshotsample
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: batch, Value: .
[INFO] Parameter: earProjectName, Value: .
[INFO] Parameter: groupId, Value: com.demo
[INFO] Parameter: dbType, Value: h2
[INFO] Parameter: artifactId, Value: snapshotsample
[WARNING] Don't override file /Users/simon/Projects/devon-ide/workspaces/main/snapshotsample/./pom.xml
[WARNING] Don't override file /Users/simon/Projects/devon-ide/workspaces/main/snapshotsample/./pom.xml
[INFO] Parent element not overwritten in /Users/simon/Projects/devon-ide/workspaces/main/snapshotsample/server/pom.xml
[INFO] Project created from Archetype in dir: /Users/simon/Projects/devon-ide/workspaces/main/snapshotsample
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.970 s
[INFO] Finished at: 2020-04-23T07:38:51+02:00
[INFO] ------------------------------------------------------------------------

```
The build gave two warnings. Please check if this is a real problem.

**Comment by maihacke** [comment]
The generated application does not run because of:

```
...
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [RevInfo]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1237) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 20 common frames omitted
```

**Comment by hohwille** [comment]
Thanks for testing.  👍  Should have done myself but too short on time so only automated tests run.
I will also remove envers from the archetype.

**Comment by hohwille** [comment]
So I removed the `@EntityScan` annotation and go back to the spring-boot default.
The auditing guide is explaining how to add it manually if someone wants to use envers.
https://github.com/devonfw/devon4j/blob/develop/documentation/guide-auditing.asciidoc#auditing
Dependency also had to be added and was never part of the archetype.

**Comment by maihacke** [comment]
> So I removed the `@EntityScan` annotation and go back to the spring-boot default.
> The auditing guide is explaining how to add it manually if someone wants to use envers.
> https://github.com/devonfw/devon4j/blob/develop/documentation/guide-auditing.asciidoc#auditing
> Dependency also had to be added and was never part of the archetype.

Thanks. Now the application is running without Envers/RevId.
I still have the warning during generation regarding the pom.xml. I assume that is not an blocker. To from my side this PR can be merged.

**Comment by hohwille** [comment]
> I still have the warning during generation regarding the pom.xml.

We can look at this later or file a separate issue for this.
Release is on the edge so lets finalize and move everything else to the next release.

**Pull request merged**
