### PR TITLE
#79: added minimum required doc files

### PR DESCRIPTION
**Pull request by hohwille**
#74: ci-friendly also for documentation/pom.xml

### CODE REVIEW

**Comment by hohwille** [comment]
So far, I did not include:
* tutorials (except the create new app one, which seemed to be the only one in a state that has any realy value, most of them only contain a TODO line)
* DB-Integration-* stuff as this is IMHO kind of obsolete and too tightly tied to specific versions, etc. (why to we have to put the minor version and patch level into the name of the asciidoc file?). We have created `guide-oracle` and `guide-hana` meanwhile. Hence, we should put in some minimal effort to turn the other ones into `guide-postgresql`, `guide-mariadb`, and `guide-mssql` with a similar scope and quality.
* `OWASP-Top-10-security-vulnerabilities` - please help me out why we created this. IMHO this looks like a duplication of what we already have in our `guide-security`. If there is anything in additionally please provide PR to get this into `guide-security`.
* Pages like `How-to-steer-an-devonfw-project-(a-guide-for-Product-Owners)` or `Managing-Secrets` should IMHO go to the general devonfw guide documentation that is not related to any of the stacks.
* In case I was missing anything else, please just provide a PR to fix :)

**Comment by hohwille** [comment]
To properly generate the new documentation this PR is connected to https://github.com/devonfw/devon-docgen/pull/6. Once the latter is merged and released I can officially update devon-docgen to `3.1.0` in this PR and it will be ready to merge.

**Comment by sjimenez77** [comment]
Thanks @hohwille for this PR. 

I agree to all your statements. 

- Tutorials entries could be removed as they will be part of the official ones. 
- I support the idea of `guide-*` approach about the supported databases configurations.
- As you said the OWASP entry should be removed from here and included as part of the documentation of the https://github.com/devonfw/devonfw-security repository.
- I fully agree also that pages like `How-to-steer-an-devonfw-project-(a-guide-for-Product-Owners)` or `Managing-Secrets` should be part of the general info of the devonfw guide. 

In the meanwhile, @dario-rodriguez is already informed about the process and is creating the CICD pipelines.

**Comment by hohwille** [comment]
@sjimenez77 thanks for the review. I updated with the final fixes and now it is ready to be merged.

**Comment by hohwille** [comment]
mhm
```
asciidoctor: WARNING: image to embed not found or not readable: /home/travis/build/devonfw/devon4j/documentation/target/generated-docs/images/t-architecture.png
asciidoctor: WARNING: image to embed not found or not readable: /home/travis/build/devonfw/devon4j/documentation/target/generated-docs/images/t-architecture.png
asciidoctor: WARNING: image to embed not found or not readable: /home/travis/build/devonfw/devon4j/documentation/target/generated-docs/images/Start-a-new-application/new_maven_project_version.PNG
asciidoctor: WARNING: allow-uri-read is not enabled; cannot embed remote image: https://cloud.githubusercontent.com/assets/11404205/7963678/43421092-0a14-11e5-86a1-ed9202674339.PNG
asciidoctor: WARNING: image to embed not found or not readable: https://cloud.githubusercontent.com/assets/11404205/7963678/43421092-0a14-11e5-86a1-ed9202674339.PNG
```

**Pull request merged**
