### PR TITLE
#347: github actions for devon4j

### PR DESCRIPTION
**Pull request by ssarmokadam**
Provides github action config for issue #347

### CODE REVIEW

**Review by hohwille — APPROVED** [review]
thanks @ssarmokadam for this PR.
Looks good to me. We will immediately try it and I therefore merge it.
If all works as expected, we can disable travis build.

One thing to notice is that PR #300 / PR #299 is now obsolete, needs to be closed and redone here for github action.

**Review by hohwille — COMMENTED** [review]
One further question: where are the secrets for deployment? IMHO this cannot work yet?!?

**Review by hohwille — CHANGES_REQUESTED** [review]
I reviewed deeper and tried to understand more of github actions and now see two problems:
* the secrets for deployment are missing so deployment will fail
* github actions does not provide repo/project secrets for PR builds. While this is a security feature preventing users from creating a PR that echos secrets in the build log, it prevents us from implementing #294 and therefore I am questioning if the migration from travis to github actions makes sense at all...

**Comment by hohwille** [comment]
OK, as I commented in #347 there seems to be a way to get all working with github action.
I try to be agile so I merge this PR already and expect another PR for #347 to improve but we can already get started and activate github actions in parallel to travis...

**Comment by hohwille** [comment]
I added secrets for SONATYPE_USER and SONATYPE_PASSWORD.
The github action build failed with this error:
```
fatal: unable to access 'https://github.com/${ORG}/${REPO_DEST}.git/': The requested URL returned error: 400
Error: Process completed with exit code 128.
```

**Comment by ssarmokadam** [comment]
@hohwille I will check and create new PR with changes required

**Comment by hohwille** [comment]
You can also just update this PR.

**Pull request merged**
